### ISSUE TITLE
deploy to production - more a "to-do" than an issue.

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#129]
I get an error when running this. 
'Specify configs in the ini-formatted file:
    /Users/swansona/.npmrc'

Pinging @srallen to run this today (ideally by lunch time chicago time) so HHMI can do soft launch. I think I'll have all the issues assigned to me done by then.

**Comment by srallen** [comment]
It sounds like there's an issue with npm or node on your local machine. I'm guessing an update to the latest versions would probably fix that. Otherwise, we're in production!
