### ISSUE TITLE
metadata bar not always aligned with subject when subjects of variable width

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#139]
I'm not sure why this is happening, since HHMI was supposed to rescale all the images to 860px, but this is happening:
![screen shot 2015-08-31 at 2 34 20 pm](https://cloud.githubusercontent.com/assets/6217406/9588493/a32d1446-5020-11e5-9767-1b29ddf828e4.png)

Given that HHMI supposedly rescaled all the images to the same width, any ideas why this is happening?

**Comment by srallen** [comment]
As discussed on slack, I'll do what I can today, but the images may need to be reprocessed to make sizes consistent.
