### ISSUE TITLE
Handle incoming data

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#147]
HHMI didn't consistently resize their images, creating issues with the metadata bar (see #139). Fixes with this are problematic (see #143), and HHMI cannot resize their images in time for launch. After conversations with @astopy we are just going to do the resize for them, and host the images in our own s3 bucket. 

The images do not have a consistent aspect ratio. I think that we should resize them all to 1000 px across, as the classifier that @srallen built has min/max display width. Happy to take alternative suggestions from @srallen and @chrissnyder on those numbers though.

@astopy I'll send you a csv with the publicly accessible raw S3 keys for all of the images. They've sent us 223,000 urls. I think it would be wise to get a small batch up and running asap - say 5-10,000 images. And then prep a much larger set in anticipation of the real launch - I'd say at least 50,000 images (if not way more, as I suspect it will be popular). I'd like to do it in batches just in case we run into any more unexpected issues!

@marten  (or @camallen) could I get you to rerun the revised script to import subjects by url after @astopy has run the resize? @astopy can give you the resulting urls for the images after he's resized them.  I've created a new subject set through PFE called soft-launch-resized and would be grateful if you could upload the initial batch to that set. I've also created a set called hard-launch-resized for the bigger batch. 

Thanks everyone!

**Comment by marten** [comment]
@camallen The revised script is here: https://github.com/zooniverse/Panoptes/commit/845b1ff3e5448bf9e58e797f88964203211a2e44, just in case you end up being the one to pick this up.

**Comment by aliburchard** [comment]
I think @srallen's fix in #150 has made this issue obsolete. We still have more images to wrangle into subject sets before hard launch (Sep 8), but @marten I will ping you about uploading those separately, since we no longer need to resize/create our own bucket.
