### ISSUE TITLE
Prompt users to sign-in

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#149]
I'm not sure if we have a prompt wired into PFE, but as a stop-gap, I'm planning to make this the last slide of the tutorial. @DarrenMcRoy would you be able to do a screencast or maybe screen shot for this/ write a quick sentence or two? I'll then add as the last tutorial slide.

**Comment by DarrenMcRoy** [comment]
Sure. Do you mean adding one more slide, or adapting the current last slide?

I could rewrite the current last slide to say "sign in and join the community" and emphasize signing in. We want to be careful about having too many tutorial slides. :-)

**Comment by aliburchard** [comment]
Hmmmm, I'm ambivalent at this point - on one hand, I like the idea of having a separate slide that says "be sure to sign in before you start!" and that's that, but on the other, I'm okay with it just being part of the existing slides.  HHMI asked that we make a separate slide, and that it be the second slide, but I don't know if that will be too disruptive. @chrislintott any thoughts based on previous experience?

**Comment by chrislintott** [comment]
Fewer slides is good. I think you have to ask why you’re prompting to log in - we actually don’t want people to go and fiddle about with login rather than getting on to classifying. Therefore I wouldn’t put it here at all

**Comment by DarrenMcRoy** [comment]
Is there no prompt anywhere else for someone to sign in? I agree with Chris, actually, upon reflection... it's probably better as a pop-up after someone's 3rd classification, or so, than as a part of the tutorial?

**Comment by aliburchard** [comment]
Oh if there were a prompt then this would be a non-issue, but there’s not. I don’t know - @chrislintott, HHMI feels really strongly that users be prompted to sign in because they’ll be doing this in classrooms. Adding this to the tutorial was a workaround that didn’t require any development effort. What do you think?

---

Alexandra Swanson, Ph.D.
Ecology & Citizen Science Postdoc
The Zooniverse
University of Oxford

**Comment by camallen** [comment]
@chrissnyder @aliburchard what's the reasoning why we don't prompt non-logged in users to sign in on wildcam?

**Comment by aliburchard** [comment]
Only because we didn't have any additional development effort. It's on the
list for as soon As Shaun starts.

On Thursday, September 17, 2015, Campbell Allen notifications@github.com
wrote:

> @chrissnyder https://github.com/chrissnyder @aliburchard
> https://github.com/aliburchard what's the reasoning why we don't prompt
> non-logged in users to sign in on wildcam?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zooniverse/wildcam-gorongosa/issues/149#issuecomment-141000351
> .

## 

Sent from my moderately intelligent phone.

**Comment by camallen** [comment]
cool - makes sense.

**Comment by chrissnyder** [comment]
Similarly we don't handle any flags that come back on subjects that also
needs to be added.
