### ISSUE TITLE
Weird image display error

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#157]
On the third trail cam photo uploaded via PFE to the "nothing here" species entry, I'm getting an unsupported media type error on the field guide page (see screenshot).

@chrissnyder any ideas?

![screen shot 2015-09-07 at 14 14 42](https://cloud.githubusercontent.com/assets/6217406/9717488/184681b4-556b-11e5-9779-b8ad851f682f.png)

Oddly, it displays just fine on the classifier...
![screen shot 2015-09-07 at 14 17 15](https://cloud.githubusercontent.com/assets/6217406/9717500/2fa9672c-556b-11e5-90f0-d404a2b848ab.png)

**Comment by chrissnyder** [comment]
Fixed.
