### ISSUE TITLE
No signup button

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/wildcam-gorongosa#164]
I'm not sure if this intentional or not. I noticed there's only a sign in button, but not a signup button. I think some new volunteers will be confused and classify non-logged in more often since the wording make it sound like you have to already be registered. 

![screen shot 2015-09-10 at 8 49 12 am](https://cloud.githubusercontent.com/assets/753325/9777594/f08067fa-5798-11e5-96b1-a307d34263bf.png)

**Comment by DarrenMcRoy** [comment]
This is definitely known -- there's no sign-up prompt whatsoever.

I'd like to get it in there as I fear that, with the press WildCam is likely to get, we might be letting potential users slip through the cracks.

However, I don't know if we have any dev time left for it.

**Comment by mschwamb** [comment]
The sign in page does have a link to the registration box so a change of text from Sign In' to "Sign In/Sign Up" might be sufficient.

**Comment by srallen** [comment]
If the change is only to change the wording of the link, then that'll be really fast and doable by us.

**Comment by chrissnyder** [comment]
Closed via #166
