### ISSUE TITLE
Stuck in tail selection

### ISSUE THREAD

**Issue by jwidness** [zooniverse/wildcam-gorongosa#167]
I was selecting filters for potential animals and opened the tail menu.  I can select different tails, but the menu won't go away, I can't hit clear, and I can't select any of the animals that show up.  I already had antelope selected, and solid pattern.  I was not able to reproduce the bug. :/

**Comment by aliburchard** [comment]
Hi @jwidness - I cannot reproduce this in any browser. Are you still having this issue? If so, would you be able to take a screen shot and provide some details (os, browser version, etc) so we can reproduce?

**Comment by jwidness** [comment]
I only had the issue once -- I wasn't able to reproduce it either.  But I did take a screenshot.  I'm using Windows 10 and Chrome Version 45.0.2454.85 m
<img width="955" alt="stuck in tail selection" src="https://cloud.githubusercontent.com/assets/13769652/9797065/42f8eca4-57c7-11e5-8cc2-1a737c996780.png">

**Comment by chrissnyder** [comment]
Please reopen if this is spotted again.
