### ISSUE TITLE
"Classify" on Talk opens in new tab... ?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/wildcam-gorongosa#168]
If as @edpaget and @aweiksnar say, the intended workflow for leaving a quick comment is to go to Talk, leave the comment, then click the "classify" link to return to classifying, why does the "classify" link currently open a new tab?

That seems like a fast way to end up with a lot of tabs...

**Comment by srallen** [comment]
This isn't really an issue here, but would be a part of the discussion here: https://github.com/zooniverse/Panoptes-Front-End/issues/863
