### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by parrish** [zooniverse/wildcam-gorongosa#173]
I get a login page, then bounces after that

`/api/me` is 500'ing as well

![signin](https://cloud.githubusercontent.com/assets/122990/9945021/7e1b0f36-5d50-11e5-98c4-7e050267ff15.gif)

**Comment by chrissnyder** [comment]
Any other details? Works fine here with my account.

Trying to create a fresh account says pretty much any username is taken. Any insight @edpaget ?

![screen shot 2015-09-17 at 3 37 01 pm](https://cloud.githubusercontent.com/assets/735191/9945292/0348b23e-5d52-11e5-8a1f-2f51d035e97f.png)

**Comment by edpaget** [comment]
I fucked up a migration it has been fixed.

**Comment by parrish** [comment]
Yep.  Fixed now
