### ISSUE TITLE
Favorites button has broken

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/wildcam-gorongosa#177]
The Favorites button in the Wildcam Gorongosa classification interface is busted.

(Some folks mentioning it here -- https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa/talk/79/7719/ -- and here -- https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa/talk/79/4819/ -- and I also tested it; doesn't work for me either.)

**Comment by DarrenMcRoy** [comment]
Here's my console:

![screen shot 2015-09-22 at 10 21 18 am](https://cloud.githubusercontent.com/assets/8987864/10022631/7d7bac86-6113-11e5-8c4c-66182574bfd8.png)

It looks like it's trying to add things to a collection that doesn't exist? Although other comments say things like "Hasn't been working for me for a few days now," which would seem to imply that it stopped working at some point.

Here's a browser console (not sure if this helps):

![screen shot 2015-09-22 at 10 24 35 am](https://cloud.githubusercontent.com/assets/8987864/10022714/dfe9e7ca-6113-11e5-89db-210422ca62c7.png)

Here's a total screenshot following some clicks of the Fav button -- nothing happens to the heart.

![screen shot 2015-09-22 at 10 21 43 am](https://cloud.githubusercontent.com/assets/8987864/10022666/a593d234-6113-11e5-8b93-2ffc9ace7fa8.png)

Any of this help @srallen ... ?

**Comment by DarrenMcRoy** [comment]
More screenshots have just gone up in #154 as well.

**Comment by srallen** [comment]
Fixed in #178. Reopen if anyone still has issues.
