### ISSUE TITLE
Cannot get to favorites/collections/profile from Gorongosa

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/wildcam-gorongosa#180]
In most places on the Zoo, you can click your name in the top right to get your profile, collections, favorites, etc.

Is there some reason that you can't do this on the WIldCam Gorongosa page?

**Comment by chrissnyder** [comment]
Maybe could be future plans, but it's Ali's call.

**Comment by aliburchard** [comment]
Let's revisit these things once Shaun starts in November.
