### ISSUE TITLE
Is signup broken from the Gorongosa home page?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/wildcam-gorongosa#181]
Just heard from someone who tried to register a new account on WildCam Gorongosa, but had no luck until she tried from the main Zooniverse page.

I can't test it because if I click the "sign in/sign up" link it just automatically signs me in with my normal Zoo login (@DZM) 

Full report:

"I've been trying to set up a new Zooinverse account (specifically for WildCam Gorongosa) and it seems the sign up process is not working.  I received a 401 error when trying to use Google to sign in, and it rejected every single username I created as taken, even extremely specific ones like variations on my full name or things like djpandapantsuit."

Then after telling her to try the main Zooniverse page:

"From the WildCam Gorongosa page, signup seems broken (both regular and using Google account) on both Safari and Chrome on a Macbook Air in OS10.10.5.  This happened both today and yesterday. However, I signed up just fine just now from the main Zooinverse page using one of the same attempted usernames.  Thanks for the suggestion and help!"

So, sign up seems to be fine from the main Zooniverse, but maybe some issues from the Gorongosa page? Can anyone else test this?

**Comment by srallen** [comment]
You can try it out via the WildCam link if you clear out your browser cookies. I just tried it out and the sign up page works. I tried sign in with Google and that's where the 401 error occurs on Google's end. This is a Panoptes issue, so please clear out your cookies, try it out and open up an issue there if you encounter errors.
