### ISSUE TITLE
Discuss Talk button link doesn't go to Talk redirects to the Zooniverse home 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/wildcam-gorongosa#183]
I think the recent change to the routing that removed the redirect if you had the no longer needed '#' in the url address is causing this.

**Comment by mschwamb** [comment]
Here's the url address it has in the navigation bar - https://www.zooniverse.org/?&&&_ga=1.268712881.1795677380.1441247630#/projects/zooniverse/wildcam-gorongosa/talk/subjects/843659

and that goes to the Zooniverse home page

**Comment by aliburchard** [comment]
Hrmmmmm. @chrissnyder or @srallen is this something you guys could have a look at?

**Comment by srallen** [comment]
Yeah I can take a look.
