### ISSUE TITLE
Design pass

### ISSUE THREAD

**Issue by heathv** [zooniverse/wildcam-gorongosa#2]
Just wanted to get this started and I'll add to it as things progress.
#### Global
- [x] Change border-radius to 6px in nav link hover and active states
- [x] Give nav hover and active states a bit more bottom padding
- [x] Footer: Use the zooniverse logo svg from the footer in the .psd. The current one is too chunky.
- [x] Nav hover: Currently dark gray 70%. Could we try using the css blend mode 'multiply' at 50%?
- [x] Default text color: Should be #304d4d instead of #222222
#### Intro cards
- [x] Add a fixed height: longer tex on some cards is causing the 'next' button to jump around.

**Comment by aliburchard** [comment]
I think we're all done with this?
