### ISSUE TITLE
Restyle beta link badge

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/wildcam-gorongosa#212]
I dunno, I think it's a bit hard to read, tbh. I've merged the original PR because it needed to be published, but I think it could use restyling, similar to other badges we've used in the past.

<img width="113" alt="screen shot 2016-04-21 at 12 26 11" src="https://cloud.githubusercontent.com/assets/2725841/14707367/5a5e8886-07bc-11e6-9101-cc5d726391ef.png">

Ref #211

**Comment by alexbfree** [comment]
Sounds like a job for @jwbmartin!

**Comment by jwbmartin** [comment]
I don't remember what other badges have looked like in the past. Does anyone have an reference images?

**Comment by simoneduca** [comment]
Superseded by https://github.com/zooniverse/wildcam-gorongosa/issues/233
