### ISSUE TITLE
Workflow id reverts to default value, even when assignment is active.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa#236]
https://github.com/zooniverse/wildcam-gorongosa-education/issues/283

**Comment by srallen** [comment]
It looks like I did break something with the assignments feature. Check out #232

**Comment by simoneduca** [comment]
Thanks Sarah. It looks like the assignment store is initialised after the workflow store, so assignment is not defined when the page first loads, when assignment store triggers new changes the workflow is set again. 

![screen shot 2016-08-17 at 16 58 27](https://cloud.githubusercontent.com/assets/8989606/17743562/02c7a700-649c-11e6-9d4e-ea3aba5abdef.png)

Do you have any thoughts?

**Comment by srallen** [comment]
Didn't get a chance to fully test out a solution, but one idea is to move the setting of the default workflow out of the init of the workflow store and into the field guide component if a workflow isn't set, so that the field guide entries will load.

**Comment by simoneduca** [comment]
Just to make sure I understand what's the expected behaviour of the field guide. Does the field guide rely on the default workflow to be set or _any_ workflow to be set?
The current staging version https://preview.zooniverse.org/wildcam-gorongosa/#/ doesn't set the default workflow in the workflow store (I removed the `else` block, as a test) and the field guide seem to work fine, even when I navigate directly to the field guide.

**Comment by simoneduca** [comment]
Ignore the above, sorry. The field guide doesn't actually work there (I clicked on aardvark and no images :()

**Comment by srallen** [comment]
The field guide depends on the workflow task to get the images for the selection: https://github.com/zooniverse/wildcam-gorongosa/blob/master/app/partials/field-guide-choice.cjsx#L25-L42

I don't know if the other workflows have the same image content, so it'd be safest to use the default workflow that the field guide was originally developed around.

**Comment by srallen** [comment]
Just thinking out loud: Maybe we should have the workflow store load up the default workflow's images in the store's init and then separately have the appropriate workflow stored for the classifier. The the field guide can listen for the default workflow images independently.

**Comment by simoneduca** [comment]
I was going with your earlier, similar idea of taking the setting of default workflow out from the store and putting it at the field guide component level. The latest is sort of the other way round, right? I'm going to have a go at the first approach if that's ok with you.

**Comment by srallen** [comment]
Sounds good. I unfortunately don't have much time to contribute to this, so which ever you find works.
