### ISSUE TITLE
Images for 'nothing here' and 'fire' choices

### ISSUE THREAD

**Issue by srallen** [zooniverse/wildcam-gorongosa#29]
The images associated with the 'nothing here' and 'fire' choices are returning a 404:

Nothing here: https://panoptes-uploads.zooniverse.org/production/workflow_attached_image/934f86c4-5484-4eae-bb2b-b8d2bd2b4341.jpeg
Fire: https://panoptes-uploads.zooniverse.org/production/workflow_attached_image/98f364f1-6da3-4d79-bbdc-1e48208636ff.jpeg

**Comment by aliburchard** [comment]
These are now uploaded and displaying properly via PFE.

**Comment by aliburchard** [comment]
And are appearing on demo site.
