### ISSUE TITLE
Add tutorial images

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#42]
@heathv I'm sure this is on your radar, but wanted to ticket up remaining to-dos so we could keep tabs on everything.

**Comment by DarrenMcRoy** [comment]
Pretty cartoon animations probably aren't needed; video screencaps of the process in action would probably do.

Although creating those might be contingent upon already having a finalized page design...

**Comment by aliburchard** [comment]
Ooh, totally agree - that would save a _lot_ of effort. Let's plan on adding those by the end of the week.

**Comment by DarrenMcRoy** [comment]
They wouldn't need to be actual videos; gifs are probably fine. :-) But they can be of the process, not those special cartoon ones that take a lot of effort.

**Comment by DarrenMcRoy** [comment]
Also, the periwinkle-blue-on-white is very hard to read; hope that's not final?

**Comment by srallen** [comment]
The styles haven't been updated since the slide tutorial was copied from mammoth-bats, so no not final.

**Comment by aliburchard** [comment]
@DarrenMcRoy will be making the screencasts on Monday (or before).

**Comment by DarrenMcRoy** [comment]
Okay, here they are, in order:

![gorongosa_tutorial_1](https://cloud.githubusercontent.com/assets/8987864/9551577/ac76c0ac-4d77-11e5-957a-ac96069fef00.jpg)

![gorongosa_tutorial_2](https://cloud.githubusercontent.com/assets/8987864/9551579/b1295baa-4d77-11e5-9fea-d1f128ab99ba.gif)

![gorongosa_tutorial_3](https://cloud.githubusercontent.com/assets/8987864/9551580/b3d0b362-4d77-11e5-93a3-710f1784a7d0.gif)

![gorongosa_tutorial_4](https://cloud.githubusercontent.com/assets/8987864/9551581/b7557a72-4d77-11e5-84ed-6f8d46db1497.gif)

![gorongosa_tutorial_5](https://cloud.githubusercontent.com/assets/8987864/9551584/b9aa082e-4d77-11e5-9d78-7793a2a325e3.jpg)
