### ISSUE TITLE
Add links to social media somewhere

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#55]
Maybe on the about pages, if we could add links to these guys?

Facebook: WildCam Gorongosa https://www.facebook.com/wildcamgorongosa?fref=ts
Twitter: @WildCamGNP https://twitter.com/WildCamGNP
Instagram: wildcamgorongosa https://instagram.com/wildcamgorongosa/

**Comment by srallen** [comment]
There are icon placeholders in the footer. I'll update them to use these links.
