### ISSUE TITLE
Add hhmi biointeractive logo to landing page 

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#58]
To meet HHMI branding requirements. 

@heathv  I'm thinking maybe a bar above or below the zooniverse bar that has the hhmi logo and maybe some text that says "made in partnership with Howard Hughes Medical Institute Biointeractive Initiative"?

Logo is attached, but I can send the eps file as well.
![hhmi_biointeractive_color_lrg](https://cloud.githubusercontent.com/assets/6217406/9488541/b15a4946-4bd2-11e5-88be-08f55c37a060.png)

**Comment by chrissnyder** [comment]
EPS would be good, as will likely need it change the color. Green on green wouldn't be so good.

**Comment by heathv** [comment]
lil' banner appearing here in the homepage design (can appear on every page, just haven't added it) http://adobe.ly/1EQZx5A

**Comment by aliburchard** [comment]
@heathv that is beautiful. 

the logo is now in public/assets/hhmi_logo_transparent.png
