### ISSUE TITLE
Move get started button above text

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/wildcam-gorongosa#61]
On small screens get started is hidden.

<img width="1136" alt="screen shot 2015-08-26 at 11 58 44" src="https://cloud.githubusercontent.com/assets/423607/9492002/97f31eba-4beb-11e5-8f10-64eff1bc61c0.png">

**Comment by aliburchard** [comment]
Is this okay? I literally just moved the buttons. Trying to avoid asking Sarah/Heath/Chris for any redesign atm.
![screen shot 2015-08-28 at 14 23 50](https://cloud.githubusercontent.com/assets/6217406/9547198/75026842-4d90-11e5-9d69-46bbe9b574f8.png)

**Comment by chrislintott** [comment]
Yes, much better

C

**Comment by DarrenMcRoy** [comment]
Hm, that's different, but I like it! :-)
