### ISSUE TITLE
Summary screen broken

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/wildcam-gorongosa#70]
We broke this at some point. Doesn't display any annotations

Doesn't need to be fancy. List annotations with their choice and answers. @heathv can add whatever pizzazz he likes.

**Comment by aliburchard** [comment]
I'm not convinced we actually need this, if it's something we can leave for now.

**Comment by chrissnyder** [comment]
Can certainly punt. Should we move on directly after clicking "Done"? What should the intermediate step be, if any?

**Comment by aliburchard** [comment]
Can we add the option to discuss or share as the intermediate step?

**Comment by srallen** [comment]
Where would the discuss button go? To the subject talk page? 

Share to social media buttons would take a bit to rebuild and I'd like to punt that to lower priority (PFE doesn't have these yet). Also, if it's just going to be a discuss button, it could potentially go in the subject 'toolbar' area where the favorite button, metadata button, and tutorial button lives.

**Comment by DarrenMcRoy** [comment]
We at least need a step where people can go to Talk to discuss a subject, or else nobody will. And that step has to come after the classification is finished, or else it risks prejudicing the classification.

My personal preference would be to have that as the intermediate step, to discuss/share, along with a markdown box that can display a rotating cast of interventions/messages/suggestions/tips.

**Comment by srallen** [comment]
Ah, I didn't think about the potential to prejudice. I can get started with at least a step with the discuss button that takes you to the subject talk page.

**Comment by chrissnyder** [comment]
To be clear, our scope for this is limited.

I personally don't think offering the ability to chat is that big a deal, and I'm pretty sure no one's done any actual testing of that theory. Space Warps was a very successful project which has a button to discuss right on the subject during the classification process.

There's a lot of interesting discussion to happen here in a general sense, but let's keep that on https://github.com/zooniverse/Panoptes-Front-End/issues/1345.

For the immediate future, adding an option to discuss is fine.

**Comment by srallen** [comment]
Spoke to @heathv and he's working on a design for the summary step.
