### ISSUE TITLE
favorite button not clickable

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#76]
this might be a known issue, but couldn't find it open.

**Comment by srallen** [comment]
Are you logged in? It's disabled when you are not logged in and should have a title on hover that prompts to sign in.

**Comment by aliburchard** [comment]
Aha. Not signed in - but when I hover over the heart, all I see is the circle with a line through it (no prompt to sign in). Also, can't actually seem to sign in, but that might be a different bug...

**Comment by srallen** [comment]
Ah, yeah that'd be a different issue. What you should see is the default browser tooltip/title on hover. If it doesn't show up at all, let me know.  

![Sign in to favorite](http://i.imgur.com/sJJbIUD.png)

**Comment by srallen** [comment]
@aliburchard Can this issue be closed?

**Comment by aliburchard** [comment]
yup!
