### ISSUE TITLE
can't sign in

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#77]
getting a "The redirect uri included is not valid." after clicking "sign in"
![screen shot 2015-08-26 at 15 18 35](https://cloud.githubusercontent.com/assets/6217406/9495919/c2203096-4c05-11e5-9236-3de625d0878e.png)

**Comment by chrissnyder** [comment]
@edpaget Could you shed some light on this? Not sure what I'm doing wrong. `http://demo.zooniverse.org/wildcam-gorongosa` is a callback URL, it works over here, and the only functionality re; sign in in this repo is the link.

**Comment by edpaget** [comment]
Doorkeeper just does a literal `redirect_url_in_database == redirect_url_in_url` comparison, so they have to exactly match. If you're just reading the current location hash and passing it as the redirect uri it'll fail if it grabs `http://demo.zooniverse.org/wildcam-gorongosa/` or `http://demo.zooniverse.org/wildcam-gorongosa/#/`. 

I've added those other cases to the Application configuration, we should revisit those rules though. Maybe it should only validate the domain?

**Comment by srallen** [comment]
Getting the same error in production on www.wildcamgorongosa.org, @edpaget or @camallen can resolve?
