### ISSUE TITLE
Identify and cancel buttons outside of container in task

### ISSUE THREAD

**Issue by srallen** [zooniverse/wildcam-gorongosa#80]
Didn't catch this with #64 initially, but a few species have long enough descriptions that it is pushing the identify and cancel buttons outside of their containers:
duiker
impala
kudu
mongoose
nyala
otter
vulture
weasel

A few options would be to fix this would be:
For those that do not need the horns question that hiding that question may be enough to keep the content in the task container, or reduce the description lengths, or adjust the css to be able to expand the container. @aliburchard, @chrissnyder let me know which is best to go forward with.

**Comment by aliburchard** [comment]
nyala, impala, and duiker are the only three species there who need the horns question. If hiding the horns question fixes the rest, I'll ask HHMI (or maybe @DarrenMcRoy) to take a stab at cutting a line from nyala, impala, and duiker.

**Comment by chrissnyder** [comment]
The height I chose was mostly arbitrary, though with the thought to keep everything on my screen at once. So we could increase the limit some, but probably not too much.
