### ISSUE TITLE
make field guide button open in new tab by default

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#86]
so that the user can keep on classifying, but have access to additional information.

Note that this is the field guide button within the classification interface.

**Comment by chrissnyder** [comment]
I had it like this, but it felt pretty awkward. Folks can always open a new tab if they'd like to.

Another potential solution would be to have a "back to classifying" button on the field guide pages if you've come from the classifier.

**Comment by DarrenMcRoy** [comment]
I'm good with either opening in a new tab or having a back-to-classifying button (that leaves the person right back where they were when classifying), but I do think we should have one or the other. Experience has taught me that many of our users don't instinctively open things in new tabs (and some may not know how), and get frustrated when they are unexpectedly taken away from the classification interface. Just my $0.02.

**Comment by aliburchard** [comment]
Yeah - I hear from volunteers often that they want things in a new tab automatically, and HHMI feels _incredibly strongly about this as well_ so I'd like to have it open in a new tab by default. 

I think if people don't like it, we'll hear about it from volunteers after launch, and can revisit.

**Comment by srallen** [comment]
For our reference in the future if React Router is used: https://github.com/rackt/react-router/issues/1510
