### ISSUE TITLE
Remove the Field Guide links

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#88]
from Fire, Nothing Here, Human, and Rodent

**Comment by aliburchard** [comment]
HHMi wants to remove links to field guide from the classification interface for these species. 

This to me is a really low priority unless it is a _super_ easy fix, but I suspect it requires us to hack a display option much like for horns. I'd rather punt until down the line.

**Comment by chrislintott** [comment]
I don’t agree with this change - I think if we can put anything at all up for the field guide (even if it’s a note about fires being part of the natural ecosystem etc) we should do. Better that than have inconsistent behaviour.

**Comment by DarrenMcRoy** [comment]
@chrislintott Funny you should mention. I wrote that exact thing as copy for @aliburchard at the end of last week. There's placeholder stuff that can go in there now that should look fine.

**Comment by aliburchard** [comment]
agreed. I've added content for non-standard pages, and the sort of silliness of this for "nothing here" will go away once "nothing here" is a persistent checkbox instead of an entry in the species list. So closing this for now.
