### ISSUE TITLE
point Talk link appropriately in top nav

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#90]
I think this is just setting the url in the top navigation bar. I'll give this a go.

I suspect I might need to ask someone @astopy ? to set up talk.wildcamgorongosa.org to pull from the pfe talk (https://www.zooniverse.org/#/projects/zooniverse/wildcam-gorongosa/talk)

**Comment by adammcmaster** [comment]
I can set up talk.wildcamgorongosa.org http://talk.wildcamgorongosa.org/ to redirect to the PFE talk page, but unless they specifically need that address for some reason it would be easier to just link directly to PFE instead.

**Comment by aliburchard** [comment]
I'm totally fine just using https://www.zooniverse.org/#/projects/zooniverse/wildcam-gorongosa/talk straight up. 

However, I've just realized that that talk page has links to PFE pages that we need to redirect as well: the main link as well as the "research" link which should point to the "about" page.

I realize redirects don't work perfectly with fragment identifiers in all browsers, but as long as we set those redirects up so people don't accidentally wind up on the PFE project, I think it's okay. 

@astopy is that you, or is that something I should bug @camallen or @edpaget for?

**Comment by edpaget** [comment]
I'm going to try to remove fragment links from the front-end very soon. I'm most of the way through getting them out of the coffee just need to figure out the right redirects server side.

**Comment by edpaget** [comment]
Whoops code not coffee. Apparently I can't edit on mobile github

**Comment by aliburchard** [comment]
Oh cool! Also, wait, there is a mobile github?!

In the meanwhile, if we want to set up redirects so that
 https://www.zooniverse.org/?reload=0#/projects/zooniverse/wildcam-gorongosa points to www.wildcamgorongosa.org 

and https://www.zooniverse.org/?reload=0#/projects/zooniverse/wildcam-gorongosa/research points to 
www.wildcam-gorongosa/about, would you be able to help with that?

Thanks!

**Comment by edpaget** [comment]
Yes once I'm off the plane I'll set those up.

**Comment by aliburchard** [comment]
great, thanks!

**Comment by aliburchard** [comment]
@edpaget is going to handle these when he's back in the office on Tuesday.

**Comment by edpaget** [comment]
@aliburchard would it be okay to just remove the research tab? There not a way to do this generically for all projects that redirect since they could have the equivelent page in a bunch of different places.

**Comment by aliburchard** [comment]
totally fine with removing research tab!

**Comment by edpaget** [comment]
I'll be done once alex merges that linked PR in.

**Comment by aliburchard** [comment]
@aweiksnar would you be able to merge @edpaget 's PR today? The project has soft-launched, and I don't want too many people poking around the PFE version :).

Thanks guys!

**Comment by aweiksnar** [comment]
Yeah can do
