### ISSUE TITLE
display bug on certain windows browsers

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa#96]
Chris Doogue reports that the demo.zooniverse.org/wildcam-gorongosa/#/ pulls up a blank page on Windows 7 firefox ESR 38.2.0, but note that this works in Chrome. 

I imagine we can do some browser testing before launching?

**Comment by srallen** [comment]
Yup, I will check over the site in a windows 7 virtual machine I have setup and I also have win10 with edge on a home desktop I can check there too (Microsoft hasn't provided VMs for the new OS yet). I'll also be checking mobile and tablet at least on iOS, too. It makes sense to do this sometime Friday afternoon after all the critical updates have been made and make fixes then. Usually the issues are CSS related when it comes to cross-browser compatibility, so I don't anticipate any major issues.

**Comment by srallen** [comment]
Just to add, the more people with various OS/browser configurations we can get to look it over the better.  I definitely can miss stuff if it's just me.

**Comment by srallen** [comment]
Is this still an issue? I checked in VM and didn't see any issues in Firefox. @ali, could you ask Chris to check again?

**Comment by aliburchard** [comment]
Will do - I'll enlist some windows users over the weekend to explore the site.

**Comment by DarrenMcRoy** [comment]
Windows 7, Firefox 40.0, works fine for me.

**Comment by aliburchard** [comment]
Awesome, thanks Darren :)
